# Generated by Django 3.1.2 on 2021-01-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
