# Generated by Django 3.1.2 on 2021-02-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tns_class',
            name='class_time',
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
    ]
