# Generated by Django 3.1.2 on 2020-12-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tns_class',
            options={'verbose_name_plural': 'TNS Class'},
        ),
        migrations.AddField(
            model_name='day',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
