# Generated by Django 3.1.2 on 2020-12-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0002_auto_20201229_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tns_class',
            options={},
        ),
        migrations.RenameField(
            model_name='tns_class',
            old_name='name',
            new_name='class_name',
        ),
    ]
