# Generated by Django 3.1.2 on 2020-12-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0003_auto_20201230_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='name',
            new_name='day',
        ),
    ]
