# Generated by Django 3.1.2 on 2020-12-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0004_auto_20201230_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
