# Generated by Django 3.1.2 on 2020-12-31 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0005_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tns_class',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tnsclasses.class_type'),
        ),
    ]
