# Generated by Django 3.1.2 on 2020-12-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0007_auto_20201231_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='further_desc',
            name='friendly_name',
        ),
        migrations.AlterField(
            model_name='further_desc',
            name='further_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
