# Generated by Django 3.1.2 on 2020-12-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0008_auto_20201231_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tns_class',
            name='further_description',
        ),
        migrations.AddField(
            model_name='tns_class',
            name='class_more_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Further_Desc',
        ),
    ]
