# Generated by Django 3.1.2 on 2021-01-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0009_auto_20201231_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_type',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
