# Generated by Django 3.1.2 on 2021-01-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0011_auto_20210116_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='class_time',
        ),
        migrations.AlterField(
            model_name='tns_class',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Class_Time',
        ),
    ]
