# Generated by Django 3.1.2 on 2021-01-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0012_auto_20210116_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tns_class',
            name='class_more_detail',
            field=models.TextField(null=True),
        ),
    ]
