# Generated by Django 3.1.2 on 2021-01-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0013_auto_20210124_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tns_class',
            name='class_time',
            field=models.TimeField(blank=True, default='23:00', null=True),
        ),
    ]
