# Generated by Django 3.1.2 on 2021-01-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0014_auto_20210124_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tns_class',
            name='class_time',
        ),
    ]
