# Generated by Django 3.1.2 on 2021-01-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0016_tns_class_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tns_class',
            name='class_time',
            field=models.TimeField(),
        ),
    ]
