# Generated by Django 3.1.2 on 2021-01-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0018_auto_20210124_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tns_class',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
