# Generated by Django 3.1.2 on 2021-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnsclasses', '0019_auto_20210124_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tns_class',
            name='class_time',
            field=models.TimeField(default='00:20', max_length=30, null=True),
        ),
    ]
